/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as OnboardingIndexImport } from './routes/onboarding.index'
import { Route as LoginIndexImport } from './routes/login.index'
import { Route as DashboardIndexImport } from './routes/dashboard.index'
import { Route as OnboardingSetUpBlogImport } from './routes/onboarding.setUpBlog'
import { Route as OnboardingRoleImport } from './routes/onboarding.role'
import { Route as OnboardingInterestsImport } from './routes/onboarding.interests'
import { Route as LoginEnterOTPImport } from './routes/login.enterOTP'
import { Route as DashboardWriteArticlePostIdImport } from './routes/dashboard.writeArticle.$postId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const OnboardingIndexRoute = OnboardingIndexImport.update({
  path: '/onboarding/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingSetUpBlogRoute = OnboardingSetUpBlogImport.update({
  path: '/onboarding/setUpBlog',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingRoleRoute = OnboardingRoleImport.update({
  path: '/onboarding/role',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingInterestsRoute = OnboardingInterestsImport.update({
  path: '/onboarding/interests',
  getParentRoute: () => rootRoute,
} as any)

const LoginEnterOTPRoute = LoginEnterOTPImport.update({
  path: '/enterOTP',
  getParentRoute: () => LoginRoute,
} as any)

const DashboardWriteArticlePostIdRoute =
  DashboardWriteArticlePostIdImport.update({
    path: '/dashboard/writeArticle/$postId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/login/enterOTP': {
      preLoaderRoute: typeof LoginEnterOTPImport
      parentRoute: typeof LoginImport
    }
    '/onboarding/interests': {
      preLoaderRoute: typeof OnboardingInterestsImport
      parentRoute: typeof rootRoute
    }
    '/onboarding/role': {
      preLoaderRoute: typeof OnboardingRoleImport
      parentRoute: typeof rootRoute
    }
    '/onboarding/setUpBlog': {
      preLoaderRoute: typeof OnboardingSetUpBlogImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof LoginImport
    }
    '/onboarding/': {
      preLoaderRoute: typeof OnboardingIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/writeArticle/$postId': {
      preLoaderRoute: typeof DashboardWriteArticlePostIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  LoginRoute.addChildren([LoginEnterOTPRoute, LoginIndexRoute]),
  OnboardingInterestsRoute,
  OnboardingRoleRoute,
  OnboardingSetUpBlogRoute,
  DashboardIndexRoute,
  OnboardingIndexRoute,
  DashboardWriteArticlePostIdRoute,
])

/* prettier-ignore-end */
